/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas.bancosListo;

import java.awt.GridLayout;
import java.util.Map;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import servicios.BaseDatos1;
import servicios.Grilla;
import ventanas.principal.FrmAjustes;

/**
 *
 * @author VictorM
 */
public class FrmBancos extends javax.swing.JFrame {
    BaseDatos1 bd = new BaseDatos1();
    Grilla miGrilla1 = new Grilla();
    FrmAjustes aj = new FrmAjustes();
    String usuarioLogeado;
    String rol;
    

    public FrmBancos() {       
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.usuarioLogeado = "VLOPEZ";
        this.setTitle("Mantenimiento de Banco - " + usuarioLogeado);
        this.restricciones();
        this.actualizarGrilla();
    }
    
    public FrmBancos(String usuLogeado, String rol) {
        initComponents();
        setLocationRelativeTo(null); 
        this.setResizable(false);
        this.usuarioLogeado = usuLogeado;        
        this.rol = rol;        
        setTitle("MANTENIMIENTO DE BANCOS - " + usuLogeado + " - " + rol);
        this.setIconImage(new ImageIcon(getClass().getResource("/iconos/svtIcono.jpeg")).getImage());
        this.restricciones();
        this.actualizarGrilla();
    }

    private void restricciones(){
        aj.soloMayusculas(txtBuscar, 50);
    }
    public void actualizarGrilla(){
        String tabla = "Bancos";
        String [] campos = {"cod_banco","nombre_banco", "tipo_cuenta_banco", "telefono_banco", "estado_banco", "uso_registro", "usuario_insercion","fecha_insercion", "usuario_modificacion", "fecha_modificacion"};
        miGrilla1.cargarGrilla(grdbanco, tabla, campos, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnNuevo1 = new javax.swing.JButton();
        btnModificarbanco = new javax.swing.JButton();
        btnEstado = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnCerrar1 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        scpContenedor = new javax.swing.JScrollPane();
        grdbanco = new javax.swing.JTable();
        btnInforme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel3.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 420, 40));

        btnNuevo1.setBackground(new java.awt.Color(204, 204, 204));
        btnNuevo1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevo.png"))); // NOI18N
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 40));

        btnModificarbanco.setBackground(new java.awt.Color(204, 204, 204));
        btnModificarbanco.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnModificarbanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/modificar.png"))); // NOI18N
        btnModificarbanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarbancoActionPerformed(evt);
            }
        });
        jPanel3.add(btnModificarbanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 70, 40));

        btnEstado.setBackground(new java.awt.Color(204, 204, 204));
        btnEstado.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/desactivar.png"))); // NOI18N
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });
        jPanel3.add(btnEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 70, 40));

        btnEliminar1.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminar1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/borrar.png"))); // NOI18N
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 70, 40));

        btnCerrar1.setBackground(new java.awt.Color(204, 204, 204));
        btnCerrar1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnCerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar.png"))); // NOI18N
        btnCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnCerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 70, 40));

        btnActualizar.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel3.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 70, 40));

        scpContenedor.setBackground(new java.awt.Color(255, 255, 255));
        scpContenedor.setAutoscrolls(true);

        grdbanco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, null));
        grdbanco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        grdbanco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "BANCO", "CUENTA", "TELEFONO", "ESTADO", "USO", "INSERSION", "FECHA INSERCION", "MODIFICACION", "FECHA MODIFICACION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grdbanco.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        grdbanco.setFillsViewportHeight(true);
        grdbanco.setRowMargin(3);
        grdbanco.setShowGrid(true);
        grdbanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdbancoMouseClicked(evt);
            }
        });
        scpContenedor.setViewportView(grdbanco);
        if (grdbanco.getColumnModel().getColumnCount() > 0) {
            grdbanco.getColumnModel().getColumn(0).setPreferredWidth(100);
            grdbanco.getColumnModel().getColumn(1).setPreferredWidth(300);
            grdbanco.getColumnModel().getColumn(2).setPreferredWidth(200);
            grdbanco.getColumnModel().getColumn(3).setPreferredWidth(150);
            grdbanco.getColumnModel().getColumn(4).setPreferredWidth(100);
            grdbanco.getColumnModel().getColumn(5).setPreferredWidth(100);
            grdbanco.getColumnModel().getColumn(6).setPreferredWidth(150);
            grdbanco.getColumnModel().getColumn(7).setPreferredWidth(150);
            grdbanco.getColumnModel().getColumn(8).setPreferredWidth(150);
            grdbanco.getColumnModel().getColumn(9).setPreferredWidth(150);
        }

        jPanel3.add(scpContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 980, 500));

        btnInforme.setBackground(new java.awt.Color(204, 204, 204));
        btnInforme.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnInforme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/informe.png"))); // NOI18N
        btnInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeActionPerformed(evt);
            }
        });
        jPanel3.add(btnInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 70, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        int fila = this.grdbanco.getSelectedRow();
        if(fila > -1){
            if(this.grdbanco.getValueAt(fila, 5).toString().equals("INACTIVO")){
                String dato = this.grdbanco.getValueAt(fila, 0).toString();
                JDEliminarBanco eBanco = new JDEliminarBanco(this, true, this, dato, usuarioLogeado);
                eBanco.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                eBanco.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "No se puede eliminar el banco por que ya se encuentra en uso");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione un registro para Eliminar");
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        int fila = this.grdbanco.getSelectedRow();
        if(fila > -1){
            if(this.grdbanco.getValueAt(fila, 4).toString().equals("ACTIVO")){
                int confirmacion = JOptionPane.showConfirmDialog(null,
                    "¿Estás seguro de que deseas desactivar este registro?",
                    "Confirmación desactivacion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

                // Comprueba la elección del usuario
                if (confirmacion == JOptionPane.YES_OPTION) {
                    bd.modificarRegistro("bancos", "estado_banco='INACTIVO'", "cod_banco=" + this.grdbanco.getValueAt(fila, 0).toString());
                    this.actualizarGrilla();
                }
            }else{
                bd.modificarRegistro("bancos", "estado_banco='ACTIVO'", "cod_banco=" + this.grdbanco.getValueAt(fila, 0).toString());
                this.actualizarGrilla();
            }
        }
    }//GEN-LAST:event_btnEstadoActionPerformed

    private void btnModificarbancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarbancoActionPerformed
        int fila = this.grdbanco.getSelectedRow();
        if(fila > -1){
            String dato = this.grdbanco.getValueAt(fila, 0).toString();
            JDModificarBanco mbanco = new JDModificarBanco(this, true, this, dato, usuarioLogeado);
            mbanco.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            mbanco.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione un registro para modificar");
        }
        }

        private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {
            
    }//GEN-LAST:event_btnModificarbancoActionPerformed

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        JDNuevoBanco nbanco= new JDNuevoBanco(this, true, this,this.usuarioLogeado);
        nbanco.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        nbanco.setVisible(true);
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        if(!this.txtBuscar.getText().isEmpty()){
            String valor = this.txtBuscar.getText();
            miGrilla1.filtrarGrilla(grdbanco, valor);
        }else{
            this.actualizarGrilla();
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        this.txtBuscar.setText(null);
        this.actualizarGrilla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void grdbancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdbancoMouseClicked
        int fila = this.grdbanco.getSelectedRow();
        if(fila > -1){
            System.out.println(fila);
            if(this.grdbanco.getValueAt(fila, 3).toString().equals("ACTIVO")){
                Icon desactivar = new ImageIcon(getClass().getResource("/iconos/desactivar.png"));
                this.btnEstado.setIcon(desactivar);
            }else{
                Icon activar = new ImageIcon(getClass().getResource("/iconos/activar.png"));
                this.btnEstado.setIcon(activar);
            }
        }
    }//GEN-LAST:event_grdbancoMouseClicked

    private void btnInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeActionPerformed
        JComboBox cboTipoCuenta = new JComboBox();
        bd.agregarItemCombo(cboTipoCuenta, 0, "TODOS");
        bd.agregarItemCombo(cboTipoCuenta, 1, "CUENTA CORRIENTE");
        bd.agregarItemCombo(cboTipoCuenta, 2, "CAJA DE AHORRO");
        cboTipoCuenta.setSelectedIndex(0);
        
        JComboBox cboEstado = new JComboBox();
        bd.agregarItemCombo(cboEstado, 0, "TODOS");
        bd.agregarItemCombo(cboEstado, 1, "ACTIVO");
        bd.agregarItemCombo(cboEstado, 2, "INACTIVO");
        cboEstado.setSelectedIndex(0);

        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(2, 2));
        panel.add(new JLabel("TIPO: "));
        panel.add(cboTipoCuenta);
        panel.add(new JLabel("ESTADO:"));
        panel.add(cboEstado);
        int imput;
        imput = JOptionPane.showConfirmDialog(this, panel, "SELECCIONE EL ESTADO", JOptionPane.DEFAULT_OPTION);

        if(imput == JOptionPane.OK_OPTION){
            String tipo = cboTipoCuenta.getSelectedItem().toString();
            String estado = cboEstado.getSelectedItem().toString();
            System.out.println(estado + " - " + tipo);

            if(estado.equals("TODOS") && tipo.equals("TODOS")){
                String url = "/reportes/reporteBancos.jasper";
                String [] nomParamet = {};
                String [] paramet = {};
                bd.llamarReporte(url, nomParamet, paramet);
                
            }else if(estado.equals("TODOS") && !tipo.equals("TODOS")){
                String url = "/reportes/reporteBancosTipoCuenta.jasper";
                String [] nomParamet = {"tipo_cuenta_banco"};
                String [] paramet = {tipo};
                bd.llamarReporte(url, nomParamet, paramet);
                
            }else if(!estado.equals("TODOS") && tipo.equals("TODOS")){
                String url = "/reportes/reporteBancosEstado.jasper";
                String [] nomParamet = {"estado_banco"};
                String [] paramet = {estado};
                bd.llamarReporte(url, nomParamet, paramet);
                
            }else if(!estado.equals("TODOS") && !tipo.equals("TODOS")){
                String url = "/reportes/reporteBancosTipoEstado.jasper";
                String [] nomParamet = {"estado_usuario", "tipo_cuenta_banco"};
                String [] paramet = {estado,tipo};
                bd.llamarReporte(url, nomParamet, paramet);
            }
        }
    }//GEN-LAST:event_btnInformeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBancos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrar1;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnInforme;
    private javax.swing.JButton btnModificarbanco;
    private javax.swing.JButton btnNuevo1;
    public static javax.swing.JTable grdbanco;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane scpContenedor;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
