/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package servicios;

import servicios.BaseDatos1;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Guillermo Villalba
 */
public class JDBackup extends javax.swing.JDialog {
    BaseDatos1 bds = new BaseDatos1();
    String usuariosLogeado;
    private int BUFFER = 10485760;  
    //para guardar en memmoria
    private StringBuffer temp = null;
    //para guardar el archivo SQL
    private FileWriter  archivo = null;
    private PrintWriter pw = null;
    private String ruta;
    
    public JDBackup(java.awt.Frame parent, boolean modal, String usuLogeado) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.usuariosLogeado = usuLogeado;
        this.setTitle("REALIZAR COPIA DE SEGURIDAD");
        SimpleDateFormat formato =  new SimpleDateFormat("dd-MM-yyyy H-mm-ss");
        txtFecha.setText(formato.format(Calendar.getInstance().getTime()).toString());
    }
    
    public boolean CrearBackup(String bd) {
        String host = bds.getHost();
        String puerto = "3307";
        String usuario = bds.getUsuBD();
        String password = bds.getContrBD();

        try {
            // Crear el comando para realizar el backup
            String[] comando = new String[] {
                "C:\\Program Files\\MySQL\\MySQL Server 5.6\\bin\\mysqldump.exe",
                "--host=" + host,
                "--port=" + puerto,
                "-u" + usuario,
                "-p" + password,
                "--routines=TRUE",
                bd
            };

            // Ejecutar el comando y obtener el resultado
            Process proceso = Runtime.getRuntime().exec(comando);
            InputStream entrada = proceso.getInputStream();
            BufferedReader lector = new BufferedReader(new InputStreamReader(entrada));
            StringBuilder contenido = new StringBuilder();
            String linea;
            while ((linea = lector.readLine()) != null) {
                contenido.append(linea).append("\n");
            }
            lector.close();
            entrada.close();

            // Verificar si el comando se ejecutó correctamente
            int codigoSalida = proceso.waitFor();
            if (codigoSalida != 0) {
                throw new IOException("Error al realizar el backup: código de salida " + codigoSalida);
            }

            // Crear el archivo de backup
            File archivo = new File(this.ruta);
            if (archivo.exists()) {
                throw new IOException("El archivo de backup ya existe");
            }
            PrintWriter escritor = new PrintWriter(new FileWriter(archivo));
            escritor.println(contenido.toString());
            escritor.close();

            return true;
        } catch (IOException e) {
            System.err.println("Error al realizar el backup: " + e.getMessage());
            return false;
        } catch (Exception e) {
            System.err.println("Error inesperado: " + e.getMessage());
            return false;
        }
    }

    public String seleccionarRutaBackup() {
        String baseDatos = bds.getBD();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar ruta para guardar el backup");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos SQL", "sql");
        fileChooser.setFileFilter(filter);

        int resultado = fileChooser.showSaveDialog(null);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            this.txtRuta.setText(archivo.getAbsolutePath()  + "\\" + baseDatos+"_" + txtFecha.getText() + "_" + this.usuariosLogeado + ".sql");
            return archivo.getAbsolutePath()  + "\\" + baseDatos+"_" + txtFecha.getText() + "_" + this.usuariosLogeado + ".sql";
        } else {
            return null;
        }
    }

    
    
    /**
     * Creates new form frmBackup
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        cmdEjecutar = new javax.swing.JButton();
        txtRuta = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSeleccionarRuta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Fecha");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 40, 30));

        txtFecha.setFocusable(false);
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 140, 30));

        cmdEjecutar.setText("Ejecutar");
        cmdEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEjecutarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdEjecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 150, 30));

        txtRuta.setBackground(new java.awt.Color(0, 0, 0));
        txtRuta.setForeground(new java.awt.Color(255, 255, 255));
        txtRuta.setFocusable(false);
        jPanel1.add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 540, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Ruta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 40, 30));

        btnSeleccionarRuta.setText("Seleccionar Ruta");
        btnSeleccionarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarRutaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEjecutarActionPerformed
        if(this.ruta != null){
            String baseDatos = bds.getBD();
            if(CrearBackup(baseDatos)){
                this.dispose();
                JOptionPane.showMessageDialog(null, "Backup realizado con éxito");
            }else{
                JOptionPane.showMessageDialog(null, "ERROR AL CREAR COPIA");
            }
        }else{
            JOptionPane.showMessageDialog(null, "DEBES SELECCIONAR LA RUTA PARA GUARDAR EL BACKUP");
        }
    }//GEN-LAST:event_cmdEjecutarActionPerformed

    private void btnSeleccionarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarRutaActionPerformed
        this.ruta = this.seleccionarRutaBackup();
    }//GEN-LAST:event_btnSeleccionarRutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDBackup dialog = new JDBackup(new javax.swing.JFrame(), true, "VLOPEZ");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionarRuta;
    private javax.swing.JButton cmdEjecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JFormattedTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
